services:
  nginx:
    image: ghcr.io/openkilt/openrepo:latest
    command: nginx
    restart: unless-stopped
    ports:
      - "7376:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      django:
        condition: service_healthy
    volumes:
      - ./openrepo-data:/var/lib/openrepo



  django:
    image: test #ghcr.io/openkilt/openrepo:latest
    expose:
      - "8000"
    command: run_openrepoweb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/login/"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - ./openrepo-data:/var/lib/openrepo
    environment:
      # - "OPENREPO_CSRF_TRUSTED_ORIGINS=myproxiedname.example.com"   #Multiple domains are space delimited"
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-}
      - OPENREPO_DB_TYPE=postgresql
      - OPENREPO_PG_DATABASE=openrepo
      - OPENREPO_PG_USERNAME=postgres
      - OPENREPO_PG_PASSWORD=${OPENREPO_PG_PASSWORD:-postgres}
      - OPENREPO_PG_HOSTNAME=db
    depends_on:
      db:
        condition: service_healthy


  worker:
    image: ghcr.io/openkilt/openrepo:latest
    command: ./django/manage.py runworker
    volumes:
      - ./openrepo-data:/var/lib/openrepo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'manage.py runworker' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-}
      - OPENREPO_DB_TYPE=postgresql
      - OPENREPO_PG_DATABASE=openrepo
      - OPENREPO_PG_USERNAME=postgres
      - OPENREPO_PG_PASSWORD=${OPENREPO_PG_PASSWORD:-postgres}
      - OPENREPO_PG_HOSTNAME=db
    depends_on:
      db:
        condition: service_healthy
      django:
        condition: service_started


  db:
    image: postgres:16-alpine3.20
    expose:
      - "5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=${OPENREPO_PG_PASSWORD:-postgres}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=openrepo
    volumes:
      - ./openrepo-data/postgres:/var/lib/postgresql/data
