# Generated by Django 4.0.7 on 2022-11-14 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.BigIntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completion_status', models.CharField(choices=[('running', 'Running'), ('complete_success', 'Completed Successfully'), ('complete_fail', 'Failed')], db_index=True, default='running', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PGPSigningKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65536)),
                ('email', models.CharField(max_length=2048)),
                ('fingerprint', models.CharField(db_index=True, max_length=65535, unique=True)),
                ('private_key_pem', models.CharField(max_length=65536)),
                ('public_key_pem', models.CharField(max_length=65536)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_uid', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('repo_type', models.CharField(choices=[('deb', 'Debian/APT'), ('rpm', 'Red Hat/RPM'), ('files', 'Generic Files')], db_index=True, max_length=128)),
                ('architecture', models.CharField(choices=[('x86_64', 'x86_64 Desktop'), ('armhf', '32-bit armhf'), ('aarch64', '64-bit arm'), ('any', 'Any')], db_index=True, max_length=128)),
                ('keep_only_latest', models.BooleanField(default=False)),
                ('package_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('refresh_count', models.BigIntegerField(default=0)),
                ('promote_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.repository')),
                ('signing_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.pgpsigningkey')),
                ('write_access', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'repositories',
            },
        ),
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repo.repository')),
            ],
        ),
        migrations.CreateModel(
            name='BuildLogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('command', models.TextField()),
                ('message', models.TextField(default='')),
                ('loglevel', models.CharField(db_index=True, max_length=128)),
                ('line_number', models.IntegerField(db_index=True)),
                ('execution_time_sec', models.FloatField(blank=True, null=True)),
                ('exec_complete', models.BooleanField(default=False)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.build')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.repository'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_uid', models.CharField(db_index=True, max_length=65536)),
                ('filename', models.CharField(max_length=65536)),
                ('package_name', models.CharField(db_index=True, max_length=65536)),
                ('version', models.CharField(db_index=True, max_length=65536)),
                ('build_date', models.DateTimeField(blank=True, null=True)),
                ('upload_date', models.DateTimeField()),
                ('checksum_sha512', models.CharField(db_index=True, max_length=512)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.repository')),
            ],
            options={
                'unique_together': {('repo', 'package_name', 'version'), ('package_uid', 'repo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='build',
            unique_together={('repo', 'build_number')},
        ),
    ]
