# Generated by Django 4.0.7 on 2022-11-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_remove_repository_architecture_package_architecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='signing_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='repo.pgpsigningkey'),
        ),
    ]
