# Generated by Django 4.0.7 on 2023-04-06 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_alter_repository_signing_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('package_uid', 'repo'), ('repo', 'package_name', 'architecture', 'version')},
        ),
    ]
