# Generated by Django 6.0.6 on 2026-06-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_uploadtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpsigningkey',
            name='passphrase',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
    ]
