# Generated by Django 6.0.6 on 2026-06-18 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0008_delete_mirror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='promote_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repo.repository'),
        ),
    ]
